# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f2220ae7a686e217d70cb14cfd7a9d296df2fe4adc6c7bfa3b6f7f3044959d037a815ac3d89e834cec0927ac5652ee20b6b3d4c43b2b0edc528cc7e9b57f21

test:
  secret_key_base: 1cbfaf6036c04cd3b3723c3ff376d9d95328a8609743bcaa01ec54455e7d1e419b495df16551b9eb54627ea6b86fee9543c2db93bdbf3711e7ae10d88e3901ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
